# Disable Jekyll processing
disable_jekyll: true

# Don't process SCSS
sass:
  load_paths: []

# Don't process any files
exclude:
  - "*.scss"
  - "*.sass"
  - "*.css"

# Set the base URL
baseurl: ""
url: "" 